<a href="https://colab.research.google.com/github/treefield00/PythonNewText4DA/blob/main/python_data_analysis_4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ■Chapter4 ライブラリによる分析の実践

---

# ▶︎4.1 NumPy

## ▶︎4.1.2　NumPyでデータを扱う

### ●1次元配列

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


### ●2次元配列

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

### ●変形　reshape

In [ ]:
c1 = np.array([0,1,2,3,4,5])
c1

array([0, 1, 2, 3, 4, 5])

In [ ]:
c2 = c1.reshape((2,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# ravelは参照を返す

c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [ ]:
# flattenはコピーを返す

c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

### ●データ型　dtype  
NumPy配列の要素のデータ型

In [ ]:
a.dtype

dtype('int64')

In [ ]:
d = np.array([1,2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [ ]:
d.dtype

dtype('int16')

In [ ]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

### ●インデックスとスライス

In [ ]:
a

array([1, 2, 3])

In [ ]:
a[0]

1

In [ ]:
a[1:]

array([2, 3])

In [ ]:
a[-1]

3

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[0]

array([1, 2, 3])

In [ ]:
b[1,0]

4

In [ ]:
b[:,2]

array([3, 6])

In [ ]:
b[1,:]

array([4, 5, 6])

In [ ]:
b[0,1:]

array([2, 3])

In [ ]:
b[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [ ]:
b[:,[2,1]]

array([[3, 2],
       [6, 5]])

### ●データ再代入

In [ ]:
a

array([1, 2, 3])

In [ ]:
a[2] = 4
a

array([1, 2, 4])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[1,2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [ ]:
b[:,2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

### ●深いコピー　copy

In [ ]:
# 参照
a1 = a
a1

array([1, 2, 4])

In [ ]:
a1[1] = 5
a1

array([1, 5, 4])

In [ ]:
a

array([1, 5, 4])

In [ ]:
# コピー

a2 = a.copy()
a2

array([1, 5, 4])

In [ ]:
a2[0] = 6
a2

array([6, 5, 4])

In [ ]:
a

array([1, 5, 4])

In [ ]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7

In [ ]:
c3

array([6, 1, 2, 3, 4, 5])

In [ ]:
c4

array([0, 7, 2, 3, 4, 5])

In [ ]:
# C3の影響
# ravel　参照　flatten コピー

c2

array([[6, 1, 2],
       [3, 4, 5]])

In [ ]:
# Python標準のlistでは、スライスした結果はコピーが渡される
# NumPyではスライスに結果は、参照が渡される

py_list1 = [0,1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [ ]:
np_array1 = np.array([0,1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


### ●数列を返す　arange

In [ ]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(11, 1, -2)

array([11,  9,  7,  5,  3])

In [ ]:
list(range(11,1,-2))

[11, 9, 7, 5, 3]

### ●乱数

In [ ]:
# 一様分布
# random関数　ranf = random = sample = random_sample
# 引数　行と列のタプル
# [0,1)の乱数
import numpy as np

f = np.random.random((3,2))
f

array([[0.06586048, 0.1168417 ],
       [0.64328504, 0.41929615],
       [0.47519446, 0.62351682]])

In [ ]:
np.random.random(1)

array([0.73679638])

In [ ]:
np.random.random((1))

array([0.48981029])

In [ ]:
np.random.random((1,))

array([0.05127517])

In [ ]:
# 一様分布
# 乱数のシード

np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [ ]:
# 一様分布
# rand関数
# 引数　２つ
# [0,1)の乱数

np.random.seed(123)
np.random.rand(4,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [ ]:
np.random.rand(4)

array([0.03778406, 0.67944405, 0.60977544, 0.83135851])

In [ ]:
np.random.rand(4,2,3)

array([[[0.73547691, 0.70547709, 0.58549241],
        [0.30825284, 0.32759523, 0.87272205]],

       [[0.21113446, 0.12931197, 0.39722243],
        [0.08717575, 0.88532229, 0.14982142]],

       [[0.07483647, 0.82484169, 0.63847477],
        [0.83372957, 0.9325541 , 0.59640435]],

       [[0.20976708, 0.47535353, 0.80818366],
        [0.56188439, 0.12782389, 0.45753145]]])

In [ ]:
# 一様分布
# randint関数
# ある範囲内の任意の整数を生成　low < high

np.random.seed(123)
np.random.randint(1,10)

3

In [ ]:
# error 引数大小が逆
np.random.randint(10,1)

ValueError: ignored

In [ ]:
# 一様分布
# 第３引数　タプル
# 多次元配列

np.random.seed(123)
np.random.randint(1,10,(3,3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [ ]:
np.random.seed(123)
np.random.randint(10, size =(3,3))

array([[2, 2, 6],
       [1, 3, 9],
       [6, 1, 0]])

In [ ]:
# 一様分布
# uniform関数　ランダムな少数値
# [第一引数, 第二引数)

np.random.seed(123)
np.random.uniform(0.0,5.0,size=(2,3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [ ]:
# 一様分布
# 第１引数と第２引数を省略すると
# デフォルト[0.0,1.0)

np.random.seed(123)
np.random.uniform(size=(4,3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

上記は一様乱数  
下記は正規分布に従った乱数

In [ ]:
# randn関数
# 標準正規分布
# 平均０　分散１

np.random.seed(123)
np.random.randn(4,2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [ ]:

# np.random.seed(123)
np.random.randn(1,1)

array([[0.99734545]])

In [ ]:
np.random.randn(1)

array([0.30239323])

In [ ]:
# normal関数
# 正規分布乱数を取得
# 引数　平均、標準偏差、size(形状)

np.random.seed(123)
np.random.normal(5,9,(4,2))

array([[ -4.77067543,  13.97610902],
       [  7.54680648,  -8.55665243],
       [ -0.20740227,  19.86292883],
       [-16.84011319,   1.13978634]])

### ●同じ要素の数列を作る

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### ●単位行列

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### ●指定値で埋める

In [ ]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [ ]:
np.full((2,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [ ]:
# np.nan
# float型 
# ndarrayは同じデータ型のみが格納できる
# nanが入っても計算できるようにfloat型

np.nan

nan

In [ ]:
type(np.nan)

float

In [ ]:
np.array([1,2,np.nan])

array([ 1.,  2., nan])

### ●範囲指定で均等割りデータを作る

In [ ]:
# 0から1までを等間隔に区切った５要素の配列

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# 0からπまでを２０等分

np.linspace(0,np.pi,21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

### ●要素間の差分

In [ ]:
l = np.array([2,2,6,1,3])
np.diff(l)

array([ 0,  4, -5,  2])

In [ ]:
m = np.array(
    [[1,2,3],
    [4,5,6]]
)
np.diff(m)

array([[1, 1],
       [1, 1]])

In [ ]:
np.diff(m, axis=0)

array([[3, 3, 3]])

In [ ]:
np.diff(m, axis=1)

array([[1, 1],
       [1, 1]])

In [ ]:
np.diff(m, axis=-1)

array([[1, 1],
       [1, 1]])

In [ ]:
np.diff(m, axis=2)

AxisError: ignored

In [ ]:
n = np.array(
    [[1,2,3],
    [4,5,6],
     [7,8,9]]
)
np.diff(n)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
np.diff(n, axis=0)

array([[3, 3, 3],
       [3, 3, 3]])

### ●連結

In [ ]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [ ]:
# 引数　リスト形式

np.concatenate([a,a1])

array([1, 5, 4, 1, 5, 4])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b1 = np.array([[10],[20]])
b1

array([[10],
       [20]])

In [ ]:
# concatenate関数
# 列方向を増やす
# 引数　リスト形式

np.concatenate([b,b1], axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [ ]:
# hstack関数
# 引数　リスト形式

np.hstack([b,b1])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [ ]:
b2 = np.array([30,60,45])
b2

array([30, 60, 45])

In [ ]:
# vstack関数

b3 = np.vstack([b,b2])
b3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [30, 60, 45]])

In [ ]:
b2_2 = np.array([[30,40,50],[60,70,80]])

b4 = np.concatenate([b,b2_2], axis=0)
b4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [30, 40, 50],
       [60, 70, 80]])

In [ ]:
b5 = np.concatenate([b,b2], axis=0)
b5

ValueError: ignored

### ●分割

In [ ]:
# hsplit関数
# 列を分割
# 第２引数　１つ目の配列が２列

first, second = np.hsplit(b3,[2])

In [ ]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [ ]:
second

array([[ 8],
       [ 8],
       [45]])

In [ ]:
# vsplit関数
# 行方向に分割
# １つ目の配列が２行

first1, second1 = np.vsplit(b3, [2])

In [ ]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [ ]:
second1

array([[30, 60, 45]])

### ●転置

In [ ]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [ ]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

### ●次元追加

reshapeでも次元変更・追加できるが、要素数を指定する必要がある  
np.newaxisの場合は、要素数を指定する必要がない

In [ ]:
a

array([1, 5, 4])

In [ ]:
# 行方向に次元追加

a[np.newaxis,:]

array([[1, 5, 4]])

In [ ]:
# 列方向に次元追加

a[:,np.newaxis]

array([[1],
       [5],
       [4]])

### ●グリッドデータ作成

In [ ]:
m = np.arange(0,4)
m

array([0, 1, 2, 3])

In [ ]:
n = np.arange(4,7)
n

array([4, 5, 6])

In [ ]:
xx, yy = np.meshgrid(m, n)

In [ ]:
# mを行方向にnの長さ分コピー
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
# nを列方向にmの長さ分コピー
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

## ▶︎4.1.3 NumPyの各機能

In [ ]:
import numpy as np

a = np.arange(3)
b = np.arange(-3,3).reshape((2,3))
c = np.arange(1,7).reshape((2,3))
d = np.arange(6).reshape((3,2))
e = np.linspace(-1,1,10)
print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d)
print("e:",e)


a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [ ]:
print("a:",a.shape)
print("b:",b.shape)
print("c:",c.shape)
print("d:",d.shape)
print("e:",e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


### ●ユニバーサルファンクション

In [ ]:
# 絶対値
print(b)
np.abs(b)

[[-3 -2 -1]
 [ 0  1  2]]


array([[3, 2, 1],
       [0, 1, 2]])

In [ ]:
# sin
print(e)
np.sin(e)

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [ ]:
# cos
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [ ]:
# log 自然対数
np.log(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718])

In [ ]:
# 常用対数
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [ ]:
# exp関数
# 自然対数の底eのe^x(e**x)
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

### ●ブロードキャスト

In [ ]:
# スカラーの加算
a

array([0, 1, 2])

In [ ]:
a + 10

array([10, 11, 12])

In [ ]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [ ]:
# 1次元配列aと２次元配列bの加算
# aが２行になったような形でbに加算される

a + b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [ ]:
a1 = a[:,np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [ ]:
# aもa1も３×３に拡張されて加算される

a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 平均を引く
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [ ]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [ ]:
# 掛け算
b*2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [ ]:
# 冪乗
b**3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [ ]:
a

array([0, 1, 2])

In [ ]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [ ]:
b - a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [ ]:
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c / a

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [ ]:
# infが出ないように、割る配列に微小値を足してから割る

c / (a + 1e-6)

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

### ●ドット積

In [ ]:
a

array([0, 1, 2])

In [ ]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [ ]:
np.dot(b,a)

array([-4,  5])

In [ ]:
b @ a

array([-4,  5])

In [ ]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [ ]:
d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [ ]:
d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

### ●判定・論理値

In [ ]:
# 配列とスカラーを演算子で比較

a > 1

array([False, False,  True])

In [ ]:
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [ ]:
# Trueの数をカウント
# 0でない要素数を出力
# Falseは０

np.count_nonzero(b > 0)


2

In [ ]:
# np.sumは要素の値を全て足す
# Trueは１として計算

np.sum(b > 0)

2

In [ ]:
# 要素の中にTrueが含まれているかどうか

np.any(b > 0)

True

In [ ]:
# 全てがTrueかどうか

np.all(b > 0)

False

In [ ]:
# 条件に合致したものだけの要素を新たな配列として出力する

b[b > 0]

array([1, 2])

In [ ]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 配列同士の比較

b == c

array([[False, False, False],
       [False, False, False]])

In [ ]:
a

array([0, 1, 2])

In [ ]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [ ]:
# １次元配列と２次元配列の比較

a == b

array([[False, False, False],
       [ True,  True,  True]])

In [ ]:
# 複数の配列の比較結果をビット演算

(b == c) | (a == b)

array([[False, False, False],
       [ True,  True,  True]])

In [ ]:
# 複数の配列のビット演算の条件に合う要素のみを配列から取得

b[(b == c) | (a == b)]

array([0, 1, 2])

In [ ]:
# 配列同士が同じ要素で構成されているか
# allclose関数は、誤差の範囲内かを見ている

np.allclose(b,c)

False

In [ ]:
# 誤差の範囲を１０とすると、Trueになる

np.allclose(b,c,atol=10)

True

### ●関数とメソッド

In [ ]:
# NumPyの関数

np.sum(a)

3

In [ ]:
# 配列のメソッド

a.sum()

3

In [ ]:
b.sum()

-3

In [ ]:
b[b > 0].sum()

3